# Send debug messages
debug: false
doMobSpawns: false
minChunkSpawnRad: 3
maxChunkSpawnRad: 7
maxCommandSpawns: 50
spawnTaskDelay: 100
mobCaps:
  CREATURE: 20
  MONSTER: 20
  WATER_CREATURE: 0
  MISC: 5
  AMBIENT: 0
playerGroupRadius: 128.0
